baseURL: "https://andersondalmina.com.br"
languageCode: "pt-BR"
title: "Ânderson Dalmina"
theme: PaperMod
paginate: 10

googleAnalytics:

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true

  homeInfoParams:
    Title: Olá, eu sou o Ander 👋
    Content: Engenheiro de software, maker e minimalista.

  socialIcons:
    - name: github
      url: "https://github.com/andersondalmina"
    - name: twitter
      url: "https://twitter.com/andersondalmina"
    - name: linkedin
      url: "https://www.linkedin.com/in/andersonzorrerdalmina"

menu:
  main:
    - identifier: arquivo
      name: Arquivo
      url: /arquivo/
      weight: 1

    - identifier: busca
      name: Busca
      url: /busca/
      weight: 2

    - identifier: sobre
      name: Sobre
      url: /sobre/
      weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON
